spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/health_sphere?sslmode=disable
    username: postgres
    password: 1305
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    # Dialektni aniq ko'rsatish xatolikning oldini oladi
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: ulugbekmominov535@gmail.com
    password: xwce hvwe gutk bdyi
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 9090

myapp:
  secret-key: c0388696-55b0-479c-a142-a2ae7cbe269a
  upload-path: C:\\Users\\HP ENVY\\uploads
#gemini:
#  api:
#    key: ${GEMINI_API_KEY}
#    url: ${GEMINI_API_URL}
ai:
  groq:
    key: ${GROQ_API_KEY}
    url: ${GROQ_API_URL}
    model: llama-3.1-8b-instant